{
 "title": "logistics",
 "time": { "from": "2021-06-17T16:59:19.000Z", "to": "1970-01-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "package transitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(recorded, '1h'),\n  kind as metric,\n  count(*) as value\nFROM package_transitions\nwhere\n  $__timeFilter(recorded)\ngroup by 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pipeline lag",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(latest_offset - successful_cursor_offset) as transitions from information_schema.pipelines_cursors where pipeline_name = 'transitions'"
    },
    {
     "rawSql": "select sum(latest_offset - successful_cursor_offset) as packages from information_schema.pipelines_cursors where pipeline_name = 'packages'"
    }
   ]
  },
  {
   "title": "volume / day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "memsql_info_schema_table_statistics_rows",
     "legendFormat": "{{table}} rowcount",
     "rawSql": "SELECT\n  $__timeGroupAlias(received,'1d'),\n  count(*) AS \"new packages\"\nFROM packages\nWHERE\n  $__timeFilter(received)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "expr": "memsql_info_schema_table_statistics_rows",
     "legendFormat": "{{table}} rowcount",
     "rawSql": "SELECT\n  $__timeGroupAlias(recorded,'1d'),\n  COUNT(*) AS 'delivered packages'\nFROM package_transitions\nWHERE\n  kind = 'delivered'\n  AND $__timeFilter(recorded)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Simulation Clock",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  date_format(max(recorded), '%Y-%m-%d %H:%i') as 'now'\nfrom package_transitions;"
    }
   ]
  },
  {
   "title": "Time Selector",
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "targets": [
    {
     "rawSql": "select\n  unix_timestamp(min(recorded)) as time_from,\n  unix_timestamp(date_add(max(recorded), interval 1 week)) as time_to,\n  \"all data\" as button_text\nfrom package_transitions;"
    },
    {
     "rawSql": "select\n  unix_timestamp(date_sub(max(recorded), interval 1 month)) as time_from,\n  unix_timestamp(date_add(max(recorded), interval 1 week)) as time_to,\n  \"last month\" as button_text\nfrom package_transitions;"
    },
    {
     "rawSql": "select\n  unix_timestamp(date_sub(max(recorded), interval 1 week)) as time_from,\n  unix_timestamp(date_add(max(recorded), interval 2 day)) as time_to,\n  \"last week\" as button_text\nfrom package_transitions;"
    }
   ]
  },
  {
   "title": "Current package destinations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n    l.city as name,\n    geography_longitude(l.lonlat) as longitude,\n    geography_latitude(l.lonlat) as latitude,\n    count(*) as metric\nFROM locations l\nINNER JOIN package_states ps ON l.locationid = ps.next_locationid\nWHERE ps.kind = 'departure_scan'\nGROUP BY 1;"
    }
   ]
  },
  {
   "title": "Current inventory",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n    l.city as name,\n    geography_longitude(l.lonlat) as longitude,\n    geography_latitude(l.lonlat) as latitude,\n    count(*) as metric\nFROM locations l\nINNER JOIN package_states ps ON l.locationid = ps.locationid\nWHERE ps.kind = 'arrival_scan'\nGROUP BY 1;"
    }
   ]
  }
 ]
}