{
 "title": "logistics real-time",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Package transitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created, '$__interval', 0),\n  kind as metric,\n  count(*) as value\nFROM package_transitions\nwhere\n  $__timeFilter(created)\ngroup by 1, 2\nORDER BY 1, 2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,'$__interval'),\n  count(*) AS \"created\"\nFROM packages\nWHERE\n  $__timeFilter(created)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Redpanda - Total number of bytes written",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_storage_log_written_bytes[$__interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Redpanda - Total number of bytes read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_storage_log_read_bytes[$__interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Ingest rate by pipeline",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start_time, '$__interval', 0) as time,\n  pipeline_name,\n  SUM(mb_per_sec)\nFROM information_schema.pipelines_batches_summary\nWHERE\n  $__timeFilter(start_time)\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  }
 ]
}